### ISSUE TITLE
create a code style and document

### ISSUE THREAD

**Issue by dhillondeep** [teamwaterloop/wlib#2]

**Comment by iazzam** [comment]
Created first draft of guide here: https://github.com/teamwaterloop/wlib/wiki/C-plus-plus-Coding-Style

**Comment by dhillondeep** [comment]
Wiki is very detailed so great job there Imad. I will review it in a bit in more detail. Now I guess if you want you can try to reformat the wlib library and the code it contains. It does not contain much code rn. I will also try to modify the code based on new standards as well. Please be sure to look at the code and comment anything unusual there and if you have any suggestions for improvements.
